feat: implement SDS gRPC for client and server
ParaParty/certdx pull request #5
Opened 2024-06-06 13:14 UTC by LDLDL

2024-06-06 15:12 UTC, tongyuantongyu requested changes
I haven't reviewed the  `pkg/client` part. I suggest some changes.

2024-06-06 16:22 UTC, ExerciseBook commented on pkg/client/client.go
> +	Stop           atomic.Pointer[chan struct{}]
I use `chan struct{}` usual, what difference among these? @tongyuantongyu

2024-06-07 02:08 UTC, LDLDL commented on pkg/server/server.go
> +var ServerCertCache = ServerCertCacheT{
Needed before, but now it is not.

2024-06-07 05:54 UTC, tongyuantongyu approved these changes

2024-06-08 12:48 UTC, merged